language: cpp

matrix:
    include:
        - os: linux
          env: CXX_LOCAL=g++-4.9 CC_LOCAL=gcc-4.9 CONFIGURATION=Release
        - os: osx
          env: CXX_LOCAL=clang++ CC_LOCAL=clang CONFIGURATION=Release

addons:
    apt:
        sources:
            - kubuntu-backports
            - ubuntu-toolchain-r-test
        packages:
            - cmake
            - gcc-4.9
            - g++-4.9

before_script:
    - mkdir build && cd build
    - CXX=$CXX_LOCAL CC=$CC_LOCAL cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION

script:
    - CXX=$CXX_LOCAL CC=$CC_LOCAL cmake --build . --config $CONFIGURATION
    - ctest -V -C $CONFIGURATION